sudo: required
service:
  - docker

before_install:
  - docker build -t aboily/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true aboily/react-test npm test

after_success:
  - docker build -t aboily/multi-client ./client
  - docker build -t aboily/multi-nginx ./nginx
  - docker build -t aboily/multi-server ./server
  - docker build -t aboily/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push then to docker hub
  - docker push aboily/multi-client
  - docker push aboily/multi-nginx
  - docker push aboily/multi-server
  - docker push aboily/multi-worker
